### ISSUE TITLE
Pengembangan repositori yang ini gimana?

### ISSUE THREAD

**Issue by adipginting** [MedanLinux/medanlinux.github.io#1]
Repo ini kemarin rencananya mau dibuat bagaimana, ya? Aku ada buat repo baru untuk kita perbaharui situs MedanLinux.com konsepnya gak tahu beda atau sama dengan tujuan awal repo ini. Kalau ternyata idenya berbeda, pengembangan paralel imo akan sangat bagus.

**Comment by fauzana** [comment]
Masih ga-je bg~ 😅

**Comment by rhonyabdullah** [comment]
bg @adipginting kalau menurut aku bg, dengan kondisi sekarang bagusnya kita fokus di 1 web aja, terserah mau kita mulai dari repo yang ini atau yang satunya karena ngebuild 2 web di 2 repo pasti ngabisin resource kita & gak efisien waktu. 

mbak @fauzana bantuin kita dong kalo gitu, join ke grup chat kita ya di https://medanlinuxcommunity.slack.com/ banyak yang mau kita benahi soalnya, hehe

**Comment by fauzana** [comment]
halooo @rhonyabdullah, gabisa join chat yah, aku ga punya email @medanlinux.com

**Comment by adipginting** [comment]
@rhonyabdullah: Oke, Bro. Masuk akal dan bisa diterima. Kita kerjain di repo satu lagi aja, ya. Kalau gak salah, di sini dulu mau dibuat web static pake mark down-nya GItHub. 
@fauzana. Bisa pm emailnya? Supaya di-invite ke Slack ya.
